checks:
  method-lines:
    config:
      threshold: 35
exclude_patterns:
- "**/node_modules/"
- "**/test/"
- "**/tests/"
- "**/__tests__/"
- "src/database/migrations"
- "src/database/seeders"
- "src/database/models"
